server:
  port: ${API_PORT:8080}

spring:
  application:
    name: releasetracker
  sql:
    init:
      platform: postgres
  datasource:
    username: ${POSTGRES_USER:postgres}
  jpa:
    properties:
      jakarta:
        persistence:
          validation:
            mode: none
      hibernate:
        query:
          fail_on_pagination_over_collection_fetch: true
    open-in-view: false
  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true